pico-8 cartridge // http://www.pico-8.com
version 39
__lua__
-- super paddle
-- by jsrn

--reload(0x6000,0,8192,"padlabel.p8"); repeat until btn()!=0

--paddle
padx=52
pady=122
padw=24
padh=4

--ball
ballx=64
bally=64
ballsize=3
ballxdir=5
ballydir=-3

score=0
lives=3

gameover = false

function movepaddle()
 if btn(0) then
  padx -= 5
 elseif btn(1) then
  padx += 5
 end
end

function moveball()
 ballx+=ballxdir
 bally+=ballydir
end

function bounceball()
 -- left
 if ballx<ballsize then
  ballxdir=-ballxdir
  sfx(1)
 end
 
 -- right
 if ballx>128-ballsize then
  ballxdir=-ballxdir
  sfx(1)
 end

 -- top
 if bally<ballsize then
  ballydir=-ballydir
  sfx(1)
 end
end

function bouncepaddle()
 if ballx>=padx and
  ballx<=padx+padw and
  bally>pady-padh then
   ballydir=-ballydir
   bally += ballydir
   score+=10
   sfx(0)
 end
end

function loseball()
 if bally<=128-ballsize then
  -- in bounds
  return
 end
 
 lives -= 1
 
 if lives <= 0 then
  -- game over
  ballydir=0
  ballxdir=0
  bally=64
  sfx(2)
  gameover=true
 else
  bally=64
  ballydir=-ballydir
  sfx(3)
 end
end

function _update()
 if gameover then
 else
  movepaddle()
  bounceball()
  bouncepaddle()
  moveball()
  loseball()
  updateheart()
 end
end

function _draw()
 -- clear screen
 rectfill(0,0,128,128,12)
 
 if gameover then
  print('game over!', 32, 60, 2)
  return
 end

 -- lives
 for i=1,lives do
  spr(heart.sprite,90+i*8, 4)
 end

 -- score
 print(score,12,6,2)
 
 -- draw paddle
 rectfill(padx,pady,padx+padw,pady+padh, 1)

 -- draw ball
 circfill(ballx,bally,ballsize,1)
end

-->8
--anims
heart = {sprite=1,cur=1,timer=0,fr=6,1,2,3,4}

function updateheart()
 heart.timer += 1
 
 if heart.timer > heart.fr then
  heart.timer = 0
  heart.cur = (heart.cur % #heart) + 1
  heart.sprite = heart[heart.cur]
 end
end

  
__gfx__
000000000000000a0000000a000a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000088088000880880000000000088088000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0070070088e8888088e888800880880a88e888800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
000770008e88888088e8888088e8888088e888800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00077000088888000888880088e88880088888000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
007007000088800000888000088888000088800a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000080a00a008000000888000000800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000a000000000000000000800000000a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
__label__
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccfffffffffffffffffffffffffffccffffffffffffff
ffffffffffffffffffffcccfffffffffffffffffffffffffffccccfffffffffffffffffffffffffcccccccccfffffffffffffffffffffffcccccffffffffffff
ffffffffffffffffffccccccccfffffffffffffffffffffffcccccccccffffffffffffffffffcccccccccccccffffffffffffffffffffccccccccccfffffffff
fffffffffffffffffccccccccccccfffffffffffffffffffcccccccccccccfffffffffffffccccccccccccccccccffffffffffffffffccccccccccccffffffff
fffffffffffffffcccccccccccccccfffffffffffffffffccccccccccccccccffffffffffcccccccccccccccccccccccffffffffffcccccccccccccccccfffff
ffffffffccccccccccccccccccccccccfffffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffff
ffffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffff
ffffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffff
ffffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffff
ffffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffff
ffffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffff
ffffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffff
ffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccceeeeeeeeccccccccccccccccccccccfffff
ffffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccceeeeeeeeeeeeeeeeccccccccccccccccccfffff
fffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccceeeeeeeeeeeeeeeeeeecccccccccccccccccfffff
fffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeccccccccccccccccccffff
ffffffccccccccccccceeeeeeeeeeeeeeeccccccccccccccccccccccccccccccccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeeecccccccccccccccccffff
ffffffccccccccccceeeeeeeeeeeeeeeeeecccccccccccccccceeeeeeecccccccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeecccccccccccccccccfff
ffffffcccccccccceeeeeeeeeeeeeeeeeeeeccccccccccccccceeeeeeecccccccceeeeeeecccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeccccccccccccccccfff
fffffccccccccccceeeeeeeeeeeeeeeeeeeeecccccccccccccceeeeeeecccccccceeeeeeeecccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeccccccccccccccccfff
fffffcccccccccceeeeeeeeeeeeeeeeeeeeeecccccccccccccceeeeeeecccccccceeeeeeeecccccccceeeeeeeeeeeeecccceeeeeeeeeeccccccccccccccccfff
fffffcccccccccceeeeeeeeeeeeeeeeeeeeeeccccccccccccceeeeeeeecccccccceeeeeeeeecccccceeeeeeeeeeeecccccceeeeeeeeeecccccccccccccccccff
fffffcccccccccceeeeeeeeeeeeeeeeeeeeeeccccccccccccceeeeeeeecccccccceeeeeeeeecccccceeeeeeeeeeecccccccceeeeeeeeecccccccccccccccccff
fffffcccccccccceeeeeeeeeeccceeeeeeeeeccccccccccccceeeeeeeecccccccceeeeeeeeecccccceeeeeeeeeecccccccccceeeeeeeecccccccccccccccccff
fffffcccccccccceeeeeeeecccccceeeeeeeeccccccccccccceeeeeeeecccccccceeeeeeeeecccccceeeeeeeeecccccccccceeeeeeeeecccccccccccccccccff
ffffffccccccccceeeeeeeeccccccceeeeeeeccccccccccccceeeeeeeeccccccccceeeeeeeeeccccceeeeeeeeccccccccccceeeeeeeeecccccccccccccccccff
fffffffcccccccceeeeeeecccccccccccccccccccccccccccceeeeeeecccccccccceeeeeeeeeccccceeeeeeeecccccccccceeeeeeeeeecccccccccccccccccff
fffffffcccccccceeeeeeecccccccceeeeeeeeecccccccccceeeeeeeeccccccccccceeeeeeeeccccceeeeeeecccccccccceeeeeeeeeeecccccccccccccccccff
ffffffffccccccceeeeeeeeccccceeeeeeeeeeeeccccccccceeeeeeeeccccccccccceeeeeeeeecccceeeeeeecccccccceeeeeeeeeeeeecccccccccccccccccff
ffffffffccccccceeeeeeeeeccceeeeeeeeeeeeeecccccccceeeeeeeeccccccccccceeeeeeeeecccceeeeeeeccccceeeeeeeeeeeeeeeccccccccccccccccccff
ffffffffccccccceeeeeeeeeeeeeeeeeeeeeeeeeecccccccceeeeeeeeccccccccccceeeeeeeeecccceeeeeeeeeeeeeeeeeeeeeeeeeeccccccccccccccccccfff
ffffffffccccccceeeeeeeeeeeeeeeeeeeeeeeeeecccccccceeeeeeeecccccccccccceeeeeeeecccceeeeeeeeeeeeeeeeeeeeeeeeeeccccccccccccccccccfff
ffffffffccccccceeeeeeeeeeeeeeeeeeeeeeeeeecccccccceeeeeeeecccccccccccceeeeeeeecccceeeeeeeeeeeeeeeeeeeeeeeeecccccccccccccccccccfff
ffffffffccccccceeeeeeeeeeeeeeeeeeeeeeeeeecccccccceeeeeeeecccccccccccceeeeeeeecccceeeeeeeeeeeeeeeeeeeeeeeecccccccccccccccccccffff
ffffffffcccccccceeeeeeeeeeeeeeeeeeeeeeeeecccccccceeeeeeeecccccccccccceeeeeeeecccceeeeeeeeeeeeeeeeeeeeeeecccccccccccccccccccfffff
ffffffffccccccccceeeeeeeeeeeeeeeeeeeeeeeecccccccceeeeeeeecccccccccccceeeeeeeecccceeeeeeeeeeeeeeeeeeeeecccccccccccccccccccccfffff
ffffffffcccccccccceeeeeeeeeeeeeeceeeeeeeecccccccceeeeeeeeeccccccccccceeeeeeeecccceeeeeeeeeeeeeeeeeecccccccccccccccccccccccffffff
ffffffffcccccccccccccceeeeeeeeccceeeeeeeeccccccccceeeeeeeeccccccccccceeeeeeeeccccceeeeeeeeccccccccccccccccccccccccccccccccffffff
ffffffffcccccccccccccccccccccccceeeeeeeeeccccccccceeeeeeeeccccccccccceeeeeeeeccccceeeeeeeeccccccccccccccccccccccccccccccccffffff
ffffffffcccccccccccccccccccccccceeeeeeeeeccccccccceeeeeeeeeccccccccceeeeeeeeeccccceeeeeeeeecccccccccccccccccccccccccccccccffffff
ffffffffccccccccccccccccccccccceeeeeeeeeeccccccccceeeeeeeeeeccccccceeeeeeeeeeccccceeeeeeeeecccccccccccccccccccccccccccccccffffff
ffffffffcccccccceeeeeeeccccccceeeeeeeeeecccccccccceeeeeeeeeeccccccceeeeeeeeeccccccceeeeeeeecccccccccccccccccccccccccccccccffffff
fffffffccccccccceeeeeeeccccceeeeeeeeeeeeccccccccccceeeeeeeeeeccccceeeeeeeeeeccccccceeeeeeeeeccccccccccccccccccccccccccccccffffff
fffffffccccccccceeeeeeeeeeeeeeeeeeeeeeeeccccccccccceeeeeeeeeeecceeeeeeeeeeeeccccccceeeeeeeeeccccccccccccccccccccccccccccccffffff
ffffffcccccccccceeeeeeeeeeeeeeeeeeeeeeecccccccccccceeeeeeeeeeeeeeeeeeeeeeeeeccccccceeeeeeeeeccccccccccccccccccccccccccccccffffff
ffffffcccccccccceeeeeeeeeeeeeeeeeeeeeeeccccccccccccceeeeeeeeeeeeeeeeeeeeeeeccccccccceeeeeeeeccccccccccccccccccccccccccccccffffff
ffffffcccccccccceeeeeeeeeeeeeeeeeeeeeeccccccccccccccceeeeeeeeeeeeeeeeeeeeecccccccccceeeeeeeeccccccccccccccccccccccccccccccffffff
fffffccccccccccceeeeeeeeeeeeeeeeeeeeecccccccccccccccceeeeeeeeeeeeeeeeeeeeccccccccccceeeeeeeeccccccccccccccccccccccccccccccffffff
ffffcccccccccccceeeeeeeeeeeeeeeeeeeecccccccccccccccccceeeeeeeeeeeeeeeeeeecccccccccccceeeeeeeccccccccccccccccccccccccccccccffffff
ffffcccccccccccccceeeeeeeeeeeeeeeeccccccccccccccccccccceeeeeeeeeeeeeeeeeccccccccccccceeeeeeeccccccccccccccccccccccccccccccffffff
ffffcccccccccccccccceeeeeeeeeeeccccccccccccccccccccccccceeeeeeeeeeeeeeccccccccccccccceeeeeeeccccccccccccccccccccccccccccccffffff
ffffccccccccccccccccccccccccccccccccccccccccccccccccccccccceeeeeeeeccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffff
ffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffff
ffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffff
fffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfff
ffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfff
ffffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfff
fffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfff
fffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfff
fffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfff
fffffffccccccccccceeeeeeeeeeeeeeeeeeccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffff
fffffffcccccccceeeeeeeeeeeeeeeeeeeeeeeccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffff
fffffffccccccceeeeeeeeeeeeeeeeeeeeeeeeecccccccccccccccccccccccccccccccccccccccccccccccceeeeeeeeeccccccccccccccccccccccccccccffff
fffffffcccccceeeeeeeeeeeeeeeeeeeeeeeeeeecccccccccccccccccceeeeeeeeeeeeeeccccccccccccccceeeeeeeeeeeeeccccccccccccccccccccccccffff
fffffffccccceeeeeeeeeeeeeeeeeeeeeeeeeeeecccccccccccccccceeeeeeeeeeeeeeeeeecccccccccccceeeeeeeeeeeeeeeeeccccccccccccccccccccfffff
fffffffccccceeeeeeeeeeeeeeeeeeeeeeeeeeeecccccccccccccceeeeeeeeeeeeeeeeeeeeeecccccccccceeeeeeeeeeeeeeeeeecccccccccccccccccccfffff
fffffffcccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeecccccccccccceeeeeeeeeeeeeeeeeeeeeeecccccccccceeeeeeeeeeeeeeeeeeeeccccccccccccccccffffff
fffffffcccceeeeeeeeeeeeccccccceeeeeeeeeeeccccccccccceeeeeeeeeeeeeeeeeeeeeeeeeccccccccceeeeeeeeeeeeeeeeeeeeecccccccccccccccffffff
fffffffcccceeeeeeeeeeccccccccccceeeeeeeeeccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeccccccceeeeeeeeeeeeeeeeeeeeeecccccccccccccccffffff
fffffffcccceeeeeeeeeccccccccccccceeeeeeeeccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeccccccceeeeeeeeeeeeeeeeeeeeeeeccccccccccccccffffff
fffffffcccceeeeeeeecccccccccccccceeeeeeeecccccccceeeeeeeeeeeeeeecceeeeeeeeeeeeccccccceeeeeeeecceeeeeeeeeeeeeccccccccccccccffffff
fffffffcccceeeeeeeecccccccccccccceeeeeeeeccccccceeeeeeeeeeeeeeccccccceeeeeeeeeccccccceeeeeeeecccceeeeeeeeeeeecccccccccccccffffff
ffffffccccceeeeeeecccccccccccccccceeeeeeeccccccceeeeeeeeeeeecccccccccceeeeeeeeccccccceeeeeeeeccccceeeeeeeeeeecccccccccccccffffff
fffffcccccceeeeeeeccccccccccccccceeeeeeeecccccceeeeeeeeeeeeccccccccccceeeeeeeeccccccceeeeeeeeccccccceeeeeeeeeeccccccccccccffffff
fffffcccccceeeeeeecccccccccccccceeeeeeeeecccccceeeeeeeeeeeccccccccccccceeeeeeeccccccceeeeeeecccccccceeeeeeeeeeccccccccccccffffff
fffffcccccceeeeeeeccccccccccccceeeeeeeeeeccccceeeeeeeeeeecccccccccccccceeeeeeeccccccceeeeeeeccccccccceeeeeeeeeccccccccccccffffff
fffffcccccceeeeeeeeeeeccccccceeeeeeeeeeeeccccceeeeeeeeeeccccccccccccccceeeeeeeecccccceeeeeeeccccccccceeeeeeeeeecccccccccccffffff
ffffccccccceeeeeeeeeeeeeeceeeeeeeeeeeeeeeccccceeeeeeeeecccccccccccccccceeeeeeeecccccceeeeeeecccccccccceeeeeeeeecccccccccccffffff
ffffccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeecccccceeeeeeeeecccccccccccccccceeeeeeeecccccceeeeeeecccccccccceeeeeeeeecccccccccccffffff
fffcccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeecccccceeeeeeeeccccccccccccccccceeeeeeeecccccceeeeeeeccccccccccceeeeeeeecccccccccccffffff
fffcccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeccccccceeeeeeeeccccccccccccccccceeeeeeeecccccceeeeeeeccccccccccceeeeeeeecccccccccccffffff
ffffccccccceeeeeeeeeeeeeeeeeeeeeeeeeeecccccccceeeeeeeccccccccccccccceeeeeeeeeeecccccceeeeeeeccccccccccceeeeeeeeccccccccccccfffff
ffffccccccceeeeeeeeeeeeeeeeeeeeeeeeecccccccccceeeeeeeccccccccccccceeeeeeeeeeeeecccccceeeeeeecccccccccccceeeeeeeccccccccccccfffff
ffffccccccceeeeeeeeeeeeeeeeeeeeeeeeccccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecccccceeeeeeecccccccccccceeeeeeeccccccccccccfffff
fffffcccccceeeeeeeceeeeeeeeeeeeecccccccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecccccceeeeeeeeccccccccccceeeeeeeccccccccccccfffff
fffffcccccceeeeeeeeccccccccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecccccceeeeeeeeccccccccccceeeeeeecccccccccccccffff
fffffcccccceeeeeeeeccccccccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecccccceeeeeeeeccccccccccceeeeeeecccccccccccccffff
fffffcccccceeeeeeeeccccccccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeccccccceeeeeeeeccccccccccceeeeeeecccccccccccccffff
fffffcccccceeeeeeeeccccccccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeccccccceeeeeeeeccccccccccceeeeeeecccccccccccccffff
fffffcccccceeeeeeeeecccccccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeccccccceeeeeeeeeccccccccceeeeeeeeccccccccccccccfff
fffffcccccceeeeeeeeecccccccccccccccccccccccccceeeeeeeccccccccccccccccceeeeeeeecccccccceeeeeeeeccccccccceeeeeeeeccccccccccccccfff
fffffccccccceeeeeeeeeccccccccccccccccccccccccceeeeeeeccccccccccccccccceeeeeeeecccccccceeeeeeeecccccccceeeeeeeeeccccccccccccccfff
fffffccccccceeeeeeeeeccccccccccccccccccccccccceeeeeeeccccccccccccccccceeeeeeeecccccccceeeeeeeeeccccccceeeeeeeeecccccccccccccffff
fffffccccccceeeeeeeeeecccccccccccccccccccccccceeeeeeeccccccccccccccccceeeeeeeecccccccceeeeeeeeeccccceeeeeeeeeeccccccccccccccffff
fffffccccccceeeeeeeeeecccccccccccccccccccccccceeeeeeeccccccccccccccccceeeeeeeecccccccceeeeeeeeecccceeeeeeeeeeecccccccccccccfffff
fffffcccccccceeeeeeeeeeccccccccccccccccccccccceeeeeeeeccccccccccccccceeeeeeeecccccccccceeeeeeeecceeeeeeeeeeeeecccccccccccccfffff
fffffcccccccceeeeeeeeeeccccccccccccccccccccccceeeeeeeeccccccccccccccceeeeeeeecccccccccceeeeeeeeeeeeeeeeeeeeeeecccccccccccccfffff
fffffccccccccceeeeeeeeeccccccccccccccccccccccceeeeeeeeccccccccccccccceeeeeeeecccccccccceeeeeeeeeeeeeeeeeeeeeeccccccccccccccfffff
fffffccccccccceeeeeeeeeccccccccccccccccccccccceeeeeeeeccccccccccccccceeeeeeeeccccccccccceeeeeeeeeeeeeeeeeeeeecccccccccccccffffff
ffffccccccccccceeeeeeeeccccccccccccccccccccccceeeeeeeeccccccccccccccceeeeeeeeccccccccccceeeeeeeeeeeeeeeeeeeeccccccccccccccffffff
ffffccccccccccceeeeeeeeccccccccccccccccccccccceeeeeeeeccccccccccccccceeeeeeeeccccccccccceeeeeeeeeeeeeeeeeeccccccccccccccccffffff
ffffcccccccccccceeeeeeecccccccccccccccccccccccceeeeeeeccccccccccccccceeeeeeeccccccccccccceeeeeeeeeeeeeeeecccccccccccccccccffffff
fffcccccccccccccccccccccccccccccccccccccccccccceeeeeeeccccccccccccccceeeeeeeccccccccccccceeeeeeeeeeeeeecccccccccccccccccccffffff
fffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccceeeeeeeccccccccccccceeeeeeeeeeeeeccccccccccccccccccccffffff
fffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccceeeeeeeccccccccccccccccccccccccccccccccccccccccccccccffffff
ffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffff
ffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffff
ffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffff
ffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffff
fffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffff
fffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffff
fffffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffff
ffffffccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffff
fffffffffffffffffccccccccccccccccccffffffffffffffccccccccccccccccccffffffffffffffffffcccccccccccccfffffffffffffffffcccccccffffff
ffffffffffffffffffffcccccccccccccffffffffffffffffffffccccccccccccffffffffffffffffffffffccccccccccffffffffffffffffffffccccccfffff
ffffffffffffffffffffffccccccccccffffffffffffffffffffffffccccccccfffffffffffffffffffffffffccccccfffffffffffffffffffffffffcccfffff
fffffffffffffffffffffffccccccffffffffffffffffffffffffffffffcccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

__sfx__
000100003405000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
001000000901000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00100000340302e0302b03026030210301d0301a03017030170300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
001000001204010030070500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
